version: '3'

services:
  backend:
      build: ./backend
      
      ports:
        - 8000:8000
      volumes:
        - ./backend:/app/backend
      expose:
        - 8000
      stdin_open: true
      tty: true
      command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  frontend:
      build: ./frontend
      environment:
        CHOKIDAR_USEPOLLING: "true"
      ports:
        - 3000:3000
      volumes:
        - ./frontend:/app/frontend
        - node-modules:/app/frontend/node_modules
      command: ["npm", "start"]
  
volumes:
  node-modules:
